""" 
✔ “List the contents of sample_data”
→ Calls list_directory("sample_data")

✔ “Read all the files in sample_data and tell me what they are”
→ Calls read_all_files("sample_data")

✔ “Read sample_data/testdata.txt”
→ Calls read_file("sample_data/testdata.txt")

✔ “What files are in the current directory?”
→ Calls list_files()
"""
# -*- coding: utf-8 -*-
"""AgentLoopWithFunctionCalling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C38Viu9JqM7SJI2Z07J3UHIjFGlYw9tC
"""

!!pip install litellm

# Important!!!
#
# <---- Set your 'OPENAI_API_KEY' as a secret over there with the "key" icon
#
#
import os
from google.colab import userdata
api_key = userdata.get('OPENAI_API_KEY')
os.environ['OPENAI_API_KEY'] = api_key



import json
import os
from typing import List, Dict, Any
from litellm import completion

# ---------------------------------------------------------
# TOOL FUNCTIONS
# ---------------------------------------------------------

def list_files() -> List[str]:
    """List files in the current directory."""
    return os.listdir(".")

def list_directory(dir_name: str) -> List[str]:
    """List files inside a specific directory."""
    try:
        return os.listdir(dir_name)
    except Exception as e:
        return [f"Error: {str(e)}"]

def read_file(file_name: str) -> str:
    """Read a file's contents."""
    try:
        with open(file_name, "r") as file:
            return file.read()
    except FileNotFoundError:
        return f"Error: {file_name} not found."
    except Exception as e:
        return f"Error: {str(e)}"

def read_all_files(dir_name: str) -> Dict[str, Any]:
    """Read all files inside a directory and return a dict of filename → content."""
    results = {}
    try:
        for item in os.listdir(dir_name):
            path = os.path.join(dir_name, item)
            if os.path.isfile(path):
                try:
                    with open(path, "r") as f:
                        results[item] = f.read()
                except Exception as e:
                    results[item] = f"Error reading file: {str(e)}"
            else:
                results[item] = "(directory)"
        return results
    except Exception as e:
        return {"error": str(e)}

def terminate(message: str) -> None:
    """Terminate the agent loop and provide a summary message."""
    print(f"Termination message: {message}")


# ---------------------------------------------------------
# TOOL DEFINITIONS FOR THE MODEL
# ---------------------------------------------------------

tools = [
    {
        "type": "function",
        "function": {
            "name": "list_files",
            "description": "Returns a list of files in the current directory.",
            "parameters": {"type": "object", "properties": {}, "required": []}
        }
    },
    {
        "type": "function",
        "function": {
            "name": "list_directory",
            "description": "Lists the contents of a specified directory.",
            "parameters": {
                "type": "object",
                "properties": {"dir_name": {"type": "string"}},
                "required": ["dir_name"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "read_file",
            "description": "Reads the content of a specified file.",
            "parameters": {
                "type": "object",
                "properties": {"file_name": {"type": "string"}},
                "required": ["file_name"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "read_all_files",
            "description": "Reads all files inside a directory and returns their contents.",
            "parameters": {
                "type": "object",
                "properties": {"dir_name": {"type": "string"}},
                "required": ["dir_name"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "terminate",
            "description": "Terminates the conversation and prints a final message.",
            "parameters": {
                "type": "object",
                "properties": {"message": {"type": "string"}},
                "required": ["message"]
            }
        }
    }
]

tool_functions = {
    "list_files": list_files,
    "list_directory": list_directory,
    "read_file": read_file,
    "read_all_files": read_all_files,
    "terminate": terminate
}

# ---------------------------------------------------------
# SYSTEM RULES
# ---------------------------------------------------------

agent_rules = [{
    "role": "system",
    "content": """
You are an AI agent that can perform tasks using tools.

Rules:
1. If the user asks about a directory, call list_directory(dir_name).
2. If the user asks to read all files in a directory, call read_all_files(dir_name).
3. If the user asks to read a specific file, call read_file(file_name).
4. Always follow the user's intent.
5. When the task is complete, call terminate(message).
"""
}]

# ---------------------------------------------------------
# AGENT LOOP
# ---------------------------------------------------------

iterations = 0
max_iterations = 10

user_task = input("What would you like me to do? ")

memory = [{"role": "user", "content": user_task}]

while iterations < max_iterations:

    messages = agent_rules + memory

    response = completion(
        model="openai/gpt-4o",
        messages=messages,
        tools=tools,
        max_tokens=1024
    )

    msg = response.choices[0].message

    # If the model wants to call a tool
    if msg.tool_calls:
        tool = msg.tool_calls[0]
        tool_name = tool.function.name
        tool_args = json.loads(tool.function.arguments)

        print(f"Executing: {tool_name} with args {tool_args}")

        if tool_name == "terminate":
            terminate(tool_args["message"])
            break

        if tool_name in tool_functions:
            try:
                result = {"result": tool_functions[tool_name](**tool_args)}
            except Exception as e:
                result = {"error": f"Error executing {tool_name}: {str(e)}"}
        else:
            result = {"error": f"Unknown tool: {tool_name}"}

        print(f"Result: {result}")

        memory.extend([
            {"role": "assistant", "content": json.dumps({"tool_name": tool_name, "args": tool_args})},
            {"role": "user", "content": json.dumps(result)}
        ])

    else:
        # Normal text response
        print("Response:", msg.content)
        break

    iterations += 1
