# -*- coding: utf-8 -*-
"""QuasiAgent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16O4yQQgRZCCs7Wn70GvSqrrl9lLOhm29
"""

!!pip install litellm

# Important!!!
#
# <---- Set your 'OPENAI_API_KEY' as a secret over there with the "key" icon
#
#
import os
from google.colab import userdata
api_key = userdata.get('OPENAI_API_KEY')
os.environ['OPENAI_API_KEY'] = api_key

"""
Exercise:
Write a program that uses sequential prompts to generate any Python function based on user input. The program should:

First Prompt:

Ask the user what function they want to create
Ask the LLM to write a basic Python function based on the user’s description
Store the response for use in subsequent prompts
Parse the response to separate the code from the commentary by the LLM
Second Prompt:

Pass the code generated from the first prompt
Ask the LLM to add comprehensive documentation including:
Function description
Parameter descriptions
Return value description
Example usage
Edge cases
Third Prompt:

Pass the documented code generated from the second prompt
Ask the LLM to add test cases using Python’s unittest framework
Tests should cover:
Basic functionality
Edge cases
Error cases
Various input scenarios
Requirements:

Use the LiteLLM library
Maintain conversation context between prompts
Print each step of the development process
Save the final version to a Python file
"""
from litellm import completion
from typing import List, Dict
import re

def generate_response(messages: List[Dict]) -> str:
    """Call LLM to get response"""
    response = completion(
        model="openai/gpt-4o",
        messages=messages,
        max_tokens=1024
    )
    return response.choices[0].message.content

def extract_code(text: str) -> str:
    """Extract Python code from LLM response"""
    match = re.search(r"```python(.*?)```", text, re.DOTALL)
    if match:
        return match.group(1).strip()
    return text.strip()  # fallback if no code fences

# ---------------------------------------------------------
# STEP 1 — Ask user what function to create
# ---------------------------------------------------------

what_function_to_create = input("What function do you want me to create?")

messages = [
    {"role": "system", "content": "You are an expert quasi agent that can code for the function, add documentation, and include test cases using the unittest framework. You will help the user based on what he wants"},
    {"role": "user", "content": f"Please code only the function in python based on user description: {what_function_to_create}"}
]


response = generate_response(messages)
base_code = extract_code(response)

print("\n=== RESPONSE 1: BASE FUNCTION ===")
print(base_code)


# ---------------------------------------------------------
# STEP 2 — Add documentation
# ---------------------------------------------------------
messages.append({"role": "assistant", "content": base_code})
messages.append({
    "role": "user",
    "content":  f"Add comprehensive documentation ONLY to this function. Include: 1) Function description, 2) Parameter descriptions, 3) Return value description, 4) Example usage, 5) Edge cases.\n\n: {base_code}"
})
response = generate_response(messages)
doc_code = extract_code(response)

print("\n=== RESPONSE 2: DOCUMENTATION ===")
print(doc_code)

# ---------------------------------------------------------
# STEP 3 — Add test case
# ---------------------------------------------------------
messages.append({"role": "assistant", "content": doc_code})
messages.append({
    "role": "user",
    "content": f"Write ONLY unittest test cases for this function. Tests must cover: 1) Basic functionality, 2) Edge cases, 3) Error cases, 4) Various input scenarios.\n\n:{doc_code}"
})
response = generate_response(messages)
test_code = extract_code(response)

print("\n=== RESPONSE 3: TEST CASES ===")
print(test_code)